//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Tarifleri_sitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Yonetici
    {
        public byte Yoneticiid { get; set; }
        public string YoneticiAd { get; set; }
        public string YoneticiSifre { get; set; }
    }
}
