//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Tarifleri_sitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GununYemegi
    {
        public short GununYemegiid { get; set; }
        public string GununYemegiAd { get; set; }
        public string GununYemegiMalzeme { get; set; }
        public string GununYemegiTarif { get; set; }
        public Nullable<byte> GununYemegiPuan { get; set; }
        public Nullable<System.DateTime> GununYemegiTarih { get; set; }
    }
}
